//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OyunArkadasım.Models.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DBTezEntities : DbContext
    {
        public DBTezEntities()
            : base("name=DBTezEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TBLOYUN> TBLOYUN { get; set; }
        public virtual DbSet<TBLUYE> TBLUYE { get; set; }
        public virtual DbSet<TBLUYEOYUNBILGI> TBLUYEOYUNBILGI { get; set; }
        public virtual DbSet<TBLDERECE> TBLDERECE { get; set; }
        public virtual DbSet<TBLROL> TBLROL { get; set; }
        public virtual DbSet<TBLMESAJLAR> TBLMESAJLAR { get; set; }
        public virtual DbSet<TBLADMIN> TBLADMIN { get; set; }
    
        public virtual ObjectResult<LolTop5_Result> LolTop5()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<LolTop5_Result>("LolTop5");
        }
    
        public virtual ObjectResult<CsTop5_Result> CsTop5()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CsTop5_Result>("CsTop5");
        }
    
        public virtual ObjectResult<ValorantTop5_Result> ValorantTop5()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ValorantTop5_Result>("ValorantTop5");
        }
    
        public virtual ObjectResult<Top5cs_Result> Top5cs()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Top5cs_Result>("Top5cs");
        }
    
        public virtual ObjectResult<Top5lol_Result> Top5lol()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Top5lol_Result>("Top5lol");
        }
    
        public virtual ObjectResult<Top5valo_Result> Top5valo()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Top5valo_Result>("Top5valo");
        }
    }
}
