//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OyunArkadasım.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLOYUN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBLOYUN()
        {
            this.TBLUYEOYUNBILGI = new HashSet<TBLUYEOYUNBILGI>();
            this.TBLDERECE = new HashSet<TBLDERECE>();
            this.TBLROL = new HashSet<TBLROL>();
        }
    
        public int ID { get; set; }
        public string OYUNADI { get; set; }
        public string FOTOGRAF { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLUYEOYUNBILGI> TBLUYEOYUNBILGI { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLDERECE> TBLDERECE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLROL> TBLROL { get; set; }
    }
}
