//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OyunArkadasım.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLROL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBLROL()
        {
            this.TBLUYEOYUNBILGI = new HashSet<TBLUYEOYUNBILGI>();
        }
    
        public int Id { get; set; }
        public string RolAdı { get; set; }
        public Nullable<int> OyunID { get; set; }
    
        public virtual TBLOYUN TBLOYUN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLUYEOYUNBILGI> TBLUYEOYUNBILGI { get; set; }
    }
}
