//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OyunArkadasım.Models.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class TBLUYE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBLUYE()
        {
            this.TBLUYEOYUNBILGI = new HashSet<TBLUYEOYUNBILGI>();
        }
    
        public int Id { get; set; }
        [StringLength(20, ErrorMessage = "Kullanıcı Adınız En Fazla 20 Karakter Uzunluğunda Olabilir !")]
        [Required(ErrorMessage = "Geçerli Bir Kullanıcı Adı Giriniz !")]
        public string KULLANICIADI { get; set; }
        [StringLength(20, ErrorMessage = "Şifreniz En Fazla 20 Karakter Uzunluğunda Olabilir !")]
        [Required(ErrorMessage = "Şifrenizi Giriniz !")]
        public string PAROLA { get; set; }
        [Required(ErrorMessage = "Geçerli Bir Mail Adresi Giriniz !")]
        public string EMAIL { get; set; }
        [Range(13, 99, ErrorMessage = "Yaşınız 13 ile 99 Arasında Olabilir !")]
        public int YAS { get; set; }
        [Required(ErrorMessage = "Adınızı Giriniz !")]
        public string AD { get; set; }
        [Required(ErrorMessage = "Soyadınızı Giriniz !")]
        public string SOYAD { get; set; }
        public Nullable<int> UYEPUAN { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLUYEOYUNBILGI> TBLUYEOYUNBILGI { get; set; }
    }
}
