//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OyunArkadasım.Models.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class TBLUYEOYUNBILGI
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBLUYEOYUNBILGI()
        {
            this.ROL1 = 10;
        }
    
        public int ID { get; set; }
        public string NICKNAME { get; set; }
        public Nullable<int> DERECESİ { get; set; }
        public int ROL1 { get; set; }
        public int OYUNID { get; set; }
        public string KARAKTERLER { get; set; }
        public int UYEID { get; set; }
        public int PUAN { get; set; }
    
        public virtual TBLOYUN TBLOYUN { get; set; }
        public virtual TBLUYE TBLUYE { get; set; }
        public virtual TBLDERECE TBLDERECE { get; set; }
        public virtual TBLROL TBLROL { get; set; }
    }
}
